input:
    input.go: |
        package structs

        // goverter:converter
        type Converter interface {
            // goverter:ignore Age
            Convert(source *Input) (*Output)

            ConvertSub(source Input) (*Output)
        }

        type Input struct {
            Name string
        }
        type Output struct {
            Name string
        }
error: |-
    Error while creating converter method:
        func (github.com/jmattheis/goverter/execution.Converter).ConvertSub(source github.com/jmattheis/goverter/execution.Input) *github.com/jmattheis/goverter/execution.Output

    | github.com/jmattheis/goverter/execution.Input
    |
    |     | github.com/jmattheis/goverter/execution.Input
    |     |
    source*
    target*
    |     |
    |     | github.com/jmattheis/goverter/execution.Output
    |
    | *github.com/jmattheis/goverter/execution.Output

    Overlapping struct settings found.

    Move these field related settings:
        goverter:ignore Age

    from the "Convert" method to a newly created method with this signature:
        func(github.com/jmattheis/goverter/execution.Input) github.com/jmattheis/goverter/execution.Output

    Goverter won't use "Convert" inside the current conversion method
    and therefore the defined field settings would be ignored.
